Shooping/Shooping/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shooping.Data;
using Shooping.Enums;
using Shooping.Helpers;

namespace Shooping.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly DataContext _context;
        private readonly IUserHelper _userHelper;

        public DashboardController(DataContext context, IUserHelper userHelper)
        {
            _context = context;
            _userHelper = userHelper;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.UsersCount = _context.Users.Count();
            ViewBag.ProductsCount = _context.Products.Count();
            ViewBag.NewOrdersCount = _context.Sales.Where(o => o.OrderStatus == OrderStatus.Nuevo).Count();
            ViewBag.ConfirmedOrdersCount = _context.Sales.Where(o => o.OrderStatus == OrderStatus.Confirmado).Count();

            return View(await _context.TemporalSales
                    .Include(u => u.User)
                    .Include(p => p.Product).ToListAsync());
        }
    }
}

Shooping/Shooping/Controllers/MesasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shooping.Data;
using Shooping.Data.Entities;
using Shooping.Helpers;
using Vereyon.Web;
using static Shooping.Helpers.ModalHelper;

namespace Shooping.Controllers
{
    [Authorize(Roles ="Admin")]
    public class MesasController : Controller
    {
        private readonly DataContext _context;
        private readonly IFlashMessage _flashMessage;

        public MesasController(DataContext context, IFlashMessage flashMessage)
        {
            _context = context;
            _flashMessage = flashMessage;
        }

        public async Task<IActionResult> Index()
        {
            return View(
                await _context.Tables
                .ToListAsync());
        }

        [NoDirectAccess]
        public async Task<IActionResult> Delete(int? id)
        {
            Table mesa = await _context.Tables.FirstOrDefaultAsync(c => c.Id == id);
            try
            {
                _context.Tables.Remove(mesa);
                await _context.SaveChangesAsync();
                _flashMessage.Info("Registro borrado.");
            }
            catch
            {
                _flashMessage.Danger("No se puede borrar la Mesa porque tiene registros relacionados.");
            }

            return RedirectToAction(nameof(Index));
        }

        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new Table());
            }
            else
            {
                Table mesa = await _context.Tables.FindAsync(id);
                if (mesa == null)
                {
                    return NotFound();
                }

                return View(mesa);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, Table mesa)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (id == 0) //Insert
                    {
                        _context.Add(mesa);
                        await _context.SaveChangesAsync();
                        _flashMessage.Info("Registro creado.");
                    }
                    else //Update
                    {
                        _context.Update(mesa);
                        await _context.SaveChangesAsync();
                        _flashMessage.Info("Registro actualizado.");
                    }
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Danger("Ya existe una Mesa con el mismo nombre y la misma cantidad de silla.");
                    }
                    else
                    {
                        _flashMessage.Danger(dbUpdateException.InnerException.Message);
                    }
                    return View(mesa);
                }
                catch (Exception exception)
                {
                    _flashMessage.Danger(exception.Message);
                    return View(mesa);
                }

                return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAll", _context.Tables.ToList()) });

            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "AddOrEdit", mesa) });
        }
    }
}

Shooping/Shooping/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shooping.Data;
using Shooping.Data.Entities;
using Shooping.Enums;
using Shooping.Helpers;
using Vereyon.Web;

namespace Shooping.Controllers
{
    public class OrdersController : Controller
    {
        private readonly DataContext _context;
        private readonly IFlashMessage _flashMessage;
        private readonly IOrdersHelper _ordersHelper;

        public OrdersController(DataContext context, IFlashMessage flashMessage, IOrdersHelper ordersHelper)
        {
            _context = context;
            _flashMessage = flashMessage;
            _ordersHelper = ordersHelper;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sales
                .Include(s => s.User)
                .Include(s => s.SaleDetails)
                .ThenInclude(sd => sd.Product)
                .ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales
                .Include(s => s.User)
                .Include(s => s.SaleDetails)
                .ThenInclude(sd => sd.Product)
                .ThenInclude(p => p.ProductImages)
                .FirstOrDefaultAsync(s => s.Id == id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Dispatch(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            if (sale.OrderStatus != OrderStatus.Nuevo)
            {
                _flashMessage.Danger("Solo se pueden despachar pedidos que estén en estado 'nuevo'.");
            }
            else
            {
                sale.OrderStatus = OrderStatus.Despachado;
                _context.Sales.Update(sale);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("El estado del pedido ha sido cambiado a 'despachado'.");
            }

            return RedirectToAction(nameof(Details), new { Id = sale.Id });
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Send(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            if (sale.OrderStatus != OrderStatus.Despachado)
            {
                _flashMessage.Danger("Solo se pueden enviar pedidos que estén en estado 'despachado'.");
            }
            else
            {
                sale.OrderStatus = OrderStatus.Enviado;
                _context.Sales.Update(sale);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("El estado del pedido ha sido cambiado a 'enviado'.");
            }

            return RedirectToAction(nameof(Details), new { Id = sale.Id });
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Confirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            if (sale.OrderStatus != OrderStatus.Enviado)
            {
                _flashMessage.Danger("Solo se pueden confirmar pedidos que estén en estado 'enviado'.");
            }
            else
            {
                sale.OrderStatus = OrderStatus.Confirmado;
                _context.Sales.Update(sale);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("El estado del pedido ha sido cambiado a 'confirmado'.");
            }

            return RedirectToAction(nameof(Details), new { Id = sale.Id });
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Cancel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            if (sale.OrderStatus == OrderStatus.Cancelado)
            {
                _flashMessage.Danger("No se puede cancelar un pedido que esté en estado 'cancelado'.");
            }
            else
            {
                await _ordersHelper.CancelOrderAsync(sale.Id);
                _flashMessage.Confirmation("El estado del pedido ha sido cambiado a 'cancelado'.");
            }

            return RedirectToAction(nameof(Details), new { Id = sale.Id });
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyOrders()
        {
            return View(await _context.Sales
                .Include(s => s.User)
                .Include(s => s.SaleDetails)
                .ThenInclude(sd => sd.Product)
                .Where(s => s.User.UserName == User.Identity.Name)
                .ToListAsync());
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales
                .Include(s => s.User)
                .Include(s => s.SaleDetails)
                .ThenInclude(sd => sd.Product)
                .ThenInclude(p => p.ProductImages)
                .FirstOrDefaultAsync(s => s.Id == id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }
    }
}

Shooping/Shooping/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shooping.Common;
using Shooping.Data;
using Shooping.Data.Entities;
using Shooping.Enums;
using Shooping.Helpers;
using Shooping.Models;

namespace Shooping.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly DataContext _context;
        private readonly IUserHelper _userHelper;
        private readonly IBlobHelper _blobHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IMailHelper _mailHelper;

        public UsersController(DataContext context, IUserHelper userHelper, IBlobHelper blobHelper, ICombosHelper combosHelper, IMailHelper mailHelper)
        {
            _context = context;
            _userHelper = userHelper;
            _blobHelper = blobHelper;
            _combosHelper = combosHelper;
            _mailHelper = mailHelper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        public async Task<IActionResult> Create()
        {
            AddUserViewModel model = new()
            {
                Id = Guid.Empty.ToString(),
                UserType = UserType.Admin,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                Guid imageId = Guid.Empty;

                if (model.ImageFile != null)
                {
                    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "users");
                }

                model.ImageId = imageId;
                User user = await _userHelper.AddUserAsync(model);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "Este correo ya está siendo usado.");
                    return View(model);
                }

                string myToken = await _userHelper.GenerateEmailConfirmationTokenAsync(user);
                string tokenLink = Url.Action("ConfirmEmail", "Account", new
                {
                    userid = user.Id,
                    token = myToken
                }, protocol: HttpContext.Request.Scheme);

                Response response = _mailHelper.SendMail(
                    $"{model.FirstName} {model.LastName}",
                    model.Username,
                    "Shopping - Confirmación de Email",
                    $"<h1>Shopping - Confirmación de Email</h1>" +
                        $"Para habilitar el usuario por favor hacer click en el siguiente link:, " +
                        $"<hr/><br/><p><a href = \"{tokenLink}\">Confirmar Email</a></p>");
                if (response.IsSuccess)
                {
                    ViewBag.Message = "Las instrucciones para habilitar el administrador han sido enviadas al correo.";
                    return View(model);
                }

                ModelState.AddModelError(string.Empty, response.Message);
            }

            return View(model);
        }
    }
}

Shooping/Shooping/Views/Shared/_AddOrEditDialog.cshtml
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">                   
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

Shooping/Shooping/Views/Shared/_BusyIndicatorPartial.cshtml
<div class="loading text-danger">
    Loading&#8230;
</div>

Shooping/Shooping/Views/Shared/_DeleteDialog.cshtml
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-blue-gradient">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estas seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"> </i> No</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete"><i class="fa fa-check-circle"> </i> Sí</button>
            </div>
        </div>
    </div>
</div>

Shooping/Shooping/Views/Shared/_FooterUser.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
        <style>
            .footerUser{
            position: relative;
            margin-top : 5rem;
            border-top: 5px solid #d92128;
         }
         </style>
    </head>

<body>
  <div class="container-fluid p-3 my-3 footerUser">
        <div class="row ">
            <div class="col-6 col-md-2 mb-3">
            </div>
            
            <div class="col-6 col-md-2 mb-3">
                <h5>Santo Somingo</h5>
                <ul class="nav flex-column">
                   
                  
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h5>Sobre Nosotros</h5>
                <ul class="nav flex-column">
                  
                 
                </ul>
            </div>
            <div class="col-6 col-md-2 mb-3">
                <h5>
                 <i class="fas fa-map-marker-alt fa-2x">
                      <a href="uyht"></a>
                </i>¿ Como llegar ?</h5>
               
                <ul class="nav flex-column">
                   

                </ul>
            </div>
         </div>

     
    <footer class="py-5 mt-2 pt-2 "> 
        <div class="row ">
                <div class="col-6 col-md-2 mb-3">
                    <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/laksita.jpg" class="logo w-100" /></a>

                </div>

            <div class="col-6 col-md-2 mb-3">
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
            </div>

            <div class="col-md-5 offset-md-1 mb-3">
                <form>
                    <h5>Subscribe to our newsletter</h5>
                    <p>Monthly digest of what's new and exciting from us.</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                        <label for="newsletter1" class="visually-hidden">Email address</label>
                        <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                        <button class="btn btn-danger" type="button">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>

       
    </footer>
  </div>
</body>
</html>

Shooping/Shooping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservyApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shooping.styles.css" asp-append-version="true" />
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Dashboard" asp-action="Index"><img src="~/images/laksita.jpg" class="logo" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex ">
                    <ul class="navbar-nav text-aling-center flex-grow-1">
                        <li class="nav-item navbar-center">
                            <i class="fa fa-tachometer-alt text-danger"></i>
                            <a class="nav-link text-white" asp-area="" asp-controller="Dashboard" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item navbar-center">
                            <i class="fa fa-list-1-2 text-danger"></i>
                            <a class="nav-link text-white" asp-area="" asp-controller="Reservations" asp-action="Index">Reservaciones</a>
                        </li>
                          <li class="nav-item navbar-center">
                            <i class="fa fa-list-1-2 text-danger"></i>
                            <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">Categoría de Productos</a>
                        </li>
                        <li class="nav-item navbar-center">
                            <i class="fa fa-list-1-2 text-danger"></i>
                            <a class="nav-link text-white" asp-area="" asp-controller="Mesas" asp-action="Index">Mesas</a>
                        </li>
                        <li class="nav-item navbar-center">
                            <i class="fa fa-list-1-2 text-danger"></i>
                            <a class="nav-link text-white" asp-area="" asp-controller="Orders" asp-action="Index">Pedidos</a>
                        </li>
                        <li class="nav-item navbar-center">
                            <i class="fa fa-list-1-2 text-danger"></i>
                            <a class="nav-link text-white" asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item navbar-center">
                            <i class="fa fa-list-1-2 text-danger"></i>
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Index">Usuarios</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Orders" asp-action="MyOrders">Mis Pedidos</a>
                            </li>
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="ChangeUser">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Logout">Cerrar Sesión</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white btn btn-outline-warning" asp-area="" asp-controller="Account" asp-action="Login">Iniciar Sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
  
    <div class="container">

        <main role="main" class="pb-3">
            <partial name="_BusyIndicatorPartial" />
            @RenderBody()
        </main>
    </div>
   @if (!User.IsInRole("Admin"))
                        {
     
    <partial name="_FooterUser" />
    <footer class="border-top footer text-muted footer-page " style="width:100%;/*position:fixed;bottom:0*/">

        <div class="container ">
           
            &copy; 2022 - Sistema de Reservaciones La kasita - <a asp-area="" asp-controller="Home" asp-action="Privacy">Políticas de Privacidad</a>
         
        </div>
       
    </footer>
     }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jasny/jasny-bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function displayBusyIndicator() {
            $('.loading').show();
        }
    </script>
    <script>
        $(window).on('beforeunload', function () {
            displayBusyIndicator();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shooping/Shooping/Views/Shared/_User.cshtml
@model Shooping.Models.EditUserViewModel

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Document" class="control-label"></label>
            <input asp-for="Document" class="form-control" />
            <span asp-validation-for="Document" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Address" class="control-label"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="PhoneNumber" class="control-label"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>    
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="ImageFile" class="control-label"></label>
            <input asp-for="ImageFile" class="form-control" type="file" />
            <span asp-validation-for="ImageFile" class="text-danger"></span>
        </div>
    </div>    
</div>