Shooping/Shooping/Models/CreateReservationViewModel.cs
namespace Shooping.Models
{
    public class CreateReservationViewModel : EditReservationViewModel
    {
    }
}

Shooping/Shooping/Models/EditReservationViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Shooping.Models;

public class EditReservationViewModel
{
    public int Id { get; set; }

    [Display(Name = "Documento")]
    [MaxLength(20, ErrorMessage = "El campo {0} debe tener máximo {1} caractéres.")]
    [Required(ErrorMessage = "El campo {0} es obligatorio.")]
    public string Document { get; set; }

    [Display(Name = "Nombre Completo")]
    [MaxLength(50, ErrorMessage = "El campo {0} debe tener máximo {1} caractéres.")]
    [Required(ErrorMessage = "El campo {0} es obligatorio.")]
    public string FullName { get; set; }

    [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd hh:mm tt}")]
    [Display(Name = "Fecha")]
    [Required(ErrorMessage = "El campo {0} es obligatorio.")]
    public DateTime Date { get; set; }

    [DataType(DataType.MultilineText)]
    [Display(Name = "Comentarios")]
    public string Remarks { get; set; }

    [Display(Name = "Mesa")]
    [Range(1, int.MaxValue, ErrorMessage = "Debes seleccionar una mesa.")]
    [Required(ErrorMessage = "El campo {0} es obligatorio.")]
    public int TableId { get; set; }

    public IEnumerable<SelectListItem> Tables { get; set; }
}

Shooping/Shooping/Controllers/ReservationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shooping.Data;
using Shooping.Data.Entities;
using Shooping.Helpers;
using Shooping.Models;
using Vereyon.Web;
using static Shooping.Helpers.ModalHelper;

namespace Shooping.Controllers;

public class ReservationsController : Controller
{
    private readonly DataContext _context;
    private readonly ICombosHelper _combosHelper;
    private readonly IBlobHelper _blobHelper;
    private readonly IFlashMessage _flashMessage;

    public ReservationsController(DataContext context, ICombosHelper combosHelper, IBlobHelper blobHelper, IFlashMessage flashMessage)
    {
        _context = context;
        _combosHelper = combosHelper;
        _blobHelper = blobHelper;
        _flashMessage = flashMessage;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _context.Reservations
            .Include(p => p.Table)
            .ToListAsync());
    }

    [NoDirectAccess]
    public async Task<IActionResult> Create()
    {
        CreateReservationViewModel model = new()
        {
            Tables = await _combosHelper.GetComboTablesAsync(),
        };

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateReservationViewModel model)
    {
        if (ModelState.IsValid)
        {
            var reservations = await _context.Reservations
                .Include(x => x.Table)
                .Where(x => x.Table.Id == model.TableId && x.Date == model.Date)
                .ToListAsync();

            if (reservations.Any())
            {
                model.Tables = await _combosHelper.GetComboTablesAsync();

                ModelState.AddModelError(nameof(CreateReservationViewModel.TableId), "Ya la mesa está reservada");

                return Json(new
                {
                    isValid = false,
                    html = RenderRazorViewToString(this, "Create", model)
                });
            }

            Reservation reservation = new()
            {
                Document = model.Document,
                Date = model.Date,
                FullName = model.FullName,
                Remarks = model.Remarks,
                Table = await _context.Tables.FindAsync(model.TableId),
            };

            try
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();

                _flashMessage.Confirmation("Registro creado.");

                return Json(new
                {
                    isValid = true,
                    html = RenderRazorViewToString(this, "_ViewAllReservations", _context.Reservations
                    .Include(p => p.Table)
                    .ToList())
                });
            }
            catch (DbUpdateException dbUpdateException)
            {
                ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
            }
            catch (Exception exception)
            {
                ModelState.AddModelError(string.Empty, exception.Message);
            }
        }

        model.Tables = await _combosHelper.GetComboTablesAsync();

        return Json(new
        {
            isValid = false,
            html = RenderRazorViewToString(this, "Create", model)
        });
    }

    [NoDirectAccess]
    public async Task<IActionResult> Edit(int id)
    {
        Reservation reservation = await _context.Reservations
            .Include(x => x.Table)
            .SingleOrDefaultAsync(x => x.Id == id);

        if (reservation == null)
        {
            return NotFound();
        }

        EditReservationViewModel model = new()
        {
            Document = reservation.Document,
            Date = reservation.Date,
            FullName = reservation.FullName,
            Remarks = reservation.Remarks,
            TableId = reservation.Table.Id,
            Tables = await _combosHelper.GetComboTablesAsync(),
        };

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, CreateReservationViewModel model)
    {
        if (id != model.Id)
        {
            return NotFound();
        }

        try
        {
            Reservation reservation = await _context.Reservations.FindAsync(model.Id);
            reservation.Document = model.Document;
            reservation.Date = model.Date;
            reservation.FullName = model.FullName;
            reservation.Remarks = model.Remarks;
            reservation.Table  = await _context.Tables.FindAsync(model.TableId);

            _context.Update(reservation);
            await _context.SaveChangesAsync();

            _flashMessage.Confirmation("Registro actualizado.");

            return Json(new
            {
                isValid = true,
                html = ModalHelper.RenderRazorViewToString(this, "_ViewAllReservations", _context.Reservations
                .Include(p => p.Table)
                .ToList())
            });
        }
        catch (DbUpdateException dbUpdateException)
        {
            ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
        }
        catch (Exception exception)
        {
            ModelState.AddModelError(string.Empty, exception.Message);
        }

        return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "Edit", model) });
    }
    /*
    public async Task<IActionResult> DeleteCategory(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        ReservationCategory productCategory = await _context.ReservationCategories
            .Include(pc => pc.Reservation)
            .FirstOrDefaultAsync(pc => pc.Id == id);
        if (productCategory == null)
        {
            return NotFound();
        }

        _context.ReservationCategories.Remove(productCategory);

        await _context.SaveChangesAsync();
        _flashMessage.Info("Registro borrado.");

        return RedirectToAction(nameof(Details), new { Id = productCategory.Reservation.Id });
    }
    */

    [NoDirectAccess]
    public async Task<IActionResult> Delete(int id)
    {
        Reservation reservation = await _context.Reservations.FirstOrDefaultAsync(p => p.Id == id);

        if (reservation == null)
        {
            return NotFound();
        }

        _context.Reservations.Remove(reservation);
        await _context.SaveChangesAsync();

        _flashMessage.Info("Registro borrado.");

        return RedirectToAction(nameof(Index));
    }
}

Shooping/Shooping/Views/Reservations/Create.cshtml
@model Shooping.Models.CreateReservationViewModel

@{
    ViewData["Title"] = "Reservaciones";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="Create" enctype="multipart/form-data" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Tables" />
            <partial name="_CreateReservation"/>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Shooping/Shooping/Views/Reservations/Edit.cshtml
@model Shooping.Models.EditReservationViewModel

@{
    ViewData["Title"] = "Reservaciones";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="Edit" enctype="multipart/form-data" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <partial name="_EditReservation"/>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Shooping/Shooping/Views/Reservations/Index.cshtml
@model IEnumerable<Shooping.Data.Entities.Reservation>

@{
    ViewData["Title"] = "Index";
}

<flash dismissable="true" />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid" style="margin-top:30px">
    <div class="card mt-2">
        <div class="card-header text-danger" style="display: block;">
            <i class="fa fa-shopping-bag"></i>  <strong>Reservaciones</strong>
            <a style="margin-left: 80%;margin-right: 0;" onclick="showInPopup('@Url.Action("Create", "Reservations", new { }, Context.Request.Scheme)' , 'Nueva Reservación')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i>Añadir</a>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAllReservations", Model)
            </div>
        </div>
    </div>
</div>

<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#ReservationsTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Reservations/Delete/', false);
    </script>
}

Shooping/Shooping/Views/Reservations/_CreateReservation.cshtml
@model Shooping.Models.CreateReservationViewModel

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Document" class="control-label"></label>
            <input asp-for="Document" class="form-control" />
            <span asp-validation-for="Document" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="FullName" class="control-label"></label>
            <input asp-for="FullName" class="form-control" />
            <span asp-validation-for="FullName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="TableId" class="control-label"></label>
            <select asp-for="TableId" asp-items="Model.Tables" class="form-control"></select>
            <span asp-validation-for="TableId" class="text-danger"></span>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Date" class="control-label"></label>
            <input asp-for="Date" type="time" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Remarks" class="control-label"></label>
            <input asp-for="Remarks" class="form-control" />
            <span asp-validation-for="Remarks" class="text-danger"></span>
        </div>
    </div>
</div>

Shooping/Shooping/Views/Reservations/_EditReservation.cshtml
@model Shooping.Models.EditReservationViewModel

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Document" class="control-label"></label>
            <input asp-for="Document" class="form-control" />
            <span asp-validation-for="Document" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="FullName" class="control-label"></label>
            <input asp-for="FullName" class="form-control" />
            <span asp-validation-for="FullName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="TableId" class="control-label"></label>
            <select asp-for="TableId" asp-items="Model.Tables" class="form-control"></select>
            <span asp-validation-for="TableId" class="text-danger"></span>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Date" class="control-label"></label>
            <input asp-for="Date" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Remarks" class="control-label"></label>
            <input asp-for="Remarks" class="form-control" />
            <span asp-validation-for="Remarks" class="text-danger"></span>
        </div>
    </div>
</div>

Shooping/Shooping/Views/Reservations/_ViewAllReservations.cshtml
@model IEnumerable<Shooping.Data.Entities.Reservation>

<table class="table table-striped table-responsive-md table-bordered smfont" id="ReservationsTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
        <col span="1" />
        <col span="1" />
        <col span="1" />
        <col span="1" />
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Document)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <a asp-action="Details" asp-controller="Reservations" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.Id)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Document)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a onclick="showInPopup('@Url.Action("Edit", "Reservations", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar Reservationo')" class="btn btn-sm btn-warning"><i class="fa fa-pencil-alt"></i> </a>
                    <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                    <button data-id="@item.Id" class="btn btn-sm btn-info" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa-regular fa-calendar"></i></button>
            </td>
        </tr>
        }
    </tbody>
</table>